sudo: required
dist: trusty

language: csharp
mono: none
dotnet: 1.0.1
solution: DepotDownloader.sln

install:
    - dotnet restore DepotDownloader.sln

script:
    - dotnet build --framework netcoreapp1.1 DepotDownloader.sln

notifications:
    irc:
        channels:
            - "irc.gamesurge.net#opensteamworks"
        on_success: never
        on_failure: always

cache:
    directories:
        - "~/.local/share/NuGet/Cache"